import { Book } from './types';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'book-1',
    title: 'Don Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    category: 'Clásicos',
    description: 'La célebre obra de la literatura española que narra las aventuras del ingenioso hidalgo y su fiel escudero Sancho Panza.',
    coverColor: 'from-[#7D6E50] to-[#5F5338] border-[#A89A7B]',
    stock: 5,
    initialStock: 10,
    price: 14.99,
  },
  {
    id: 'book-2',
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    category: 'Realismo Mágico',
    description: 'La cautivadora historia de la familia Buendía a lo largo de siete generaciones en el mítico pueblo de Macondo.',
    coverColor: 'from-[#5F6F52] to-[#45523A] border-[#889C79]',
    stock: 3,
    initialStock: 8,
    price: 12.50,
  },
  {
    id: 'book-3',
    title: '1984',
    author: 'George Orwell',
    category: 'Ciencia Ficción / Distopía',
    description: 'Una visión sombría y poderosa de una sociedad bajo el control absoluto de un estado totalitario representado por el Gran Hermano.',
    coverColor: 'from-[#3D3D33] to-[#25251F] border-[#666657]',
    stock: 2,
    initialStock: 5,
    price: 9.99,
  },
  {
    id: 'book-4',
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    category: 'Fantasía / Infantil',
    description: 'Un viaje poético y filosófico a través de las estrellas que revela la belleza de la inocencia y el valor del amor verdadero.',
    coverColor: 'from-[#A67B5B] to-[#785437] border-[#CBA386]',
    stock: 1, // Easy to trigger stock zero!
    initialStock: 6,
    price: 7.50,
  },
  {
    id: 'book-5',
    title: 'Hábitos Atómicos',
    author: 'James Clear',
    category: 'Desarrollo Personal',
    description: 'Un método sencillo y eficaz para desarrollar buenos hábitos y eliminar los malos mediante pequeños cambios diarios de gran impacto.',
    coverColor: 'from-[#827D6C] to-[#5A564A] border-[#ADA795]',
    stock: 4,
    initialStock: 6,
    price: 16.00,
  },
  {
    id: 'book-6',
    title: 'Sapiens: De animales a dioses',
    author: 'Yuval Noah Harari',
    category: 'Historia',
    description: 'Un viaje fascinante a través de la historia de nuestra especie, desde los primeros homínidos hasta los avances tecnológicos actuales.',
    coverColor: 'from-[#556B2F] to-[#39491F] border-[#819D55]',
    stock: 0, // Starts at 0 to showcase the active stock notifications immediately!
    initialStock: 5,
    price: 22.00,
  },
  {
    id: 'book-7',
    title: 'El Hobbit',
    author: 'J.R.R. Tolkien',
    category: 'Fantasía de Aventuras',
    description: 'La magnífica precuela de El Señor de los Anillos, donde el hobbit Bilbo Bolsón emprende una peligrosa búsqueda con enanos y un mago.',
    coverColor: 'from-[#8F7D66] to-[#61513D] border-[#B9A68F]',
    stock: 6,
    initialStock: 10,
    price: 11.25,
  },
  {
    id: 'book-8',
    title: 'Rayuela',
    author: 'Julio Cortázar',
    category: 'Literatura Latinoamericana',
    description: 'Una novela revolucionaria estructurada para ser leída en diferentes órdenes, siguiendo el viaje existencial de Horacio Oliveira.',
    coverColor: 'from-[#4A5D4E] to-[#313E34] border-[#728B77]',
    stock: 3,
    initialStock: 6,
    price: 13.50,
  }
];
